### PR TITLE
condensed the if statements

### LINKED ISSUE #3: Shorten Python_encryption_idea
https://github.com/ExploreWithCode/Python_mini_projects/labels/help%20wanted [here](https://github.com/ExploreWithCode/Python_mini_projects/blob/main/Python_encryption_idea.py)
The idea is to not have to specify what happens to every letter individually.

### PR DESCRIPTION
**Pull request by Nolan-OC**
I condensed a lot of the if statements and conditionals down by swapping between an uppercase and lowercase alphabet. If you want to expand that part out to be a little more readable I think that would be a fine idea

### CODE REVIEW

**Review by ExploreWithCode — APPROVED** [review]
It works and it is as short as I wanted. Thank you!
I won't pretend that I get 100% of it, but I can grasp the general idea.
We certainly will have the ability to make changes if we wanted or needed to and you are welcomed to do that.

**Comment by ExploreWithCode** [comment]
@Nolan-OC After merging the commit into the main branch, I cannot acess the other files. Do I revert the merge and accept only this single commit into the main branch?

**Comment by Nolan-OC** [comment]
Yes did you get it working? I only changed the one file so if you merge that one it should be fine.

**Comment by ExploreWithCode** [comment]
> 

Everything is fine on my phone, but I get an error on the computer. "Looks like something went wrong". 🤷‍♂️

**Comment by Nolan-OC** [comment]
that's very strange I'm not sure how to help sorry :/

**Comment by vishalyadav98** [comment]
[Banner](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
valterlobo, @Shaeid317, @anasaboayham, @najmahmd, @SONVICHETH, @Tawfig0505, @komaev, @freeman3465, @dNESHGARG, @tonyxu1, @Kunnunicky, @fairhopeweb, @tabullarasa, @maipttKrystal, @senula8982, @Yanz456aya123, @Roobinhan, @sisoctagon, @garyhtou, @vehicles4real, @Jeffreytt5, @HalilKayrak, @quayhoian, @vikmeup, @davirds, @jack3536, @Jones098, @mohaway2000, @dac, @Regard4, @chibong, @Claireeze74, @Ramly7878, @Apoll95, @Jjcent, @EvmosSupport, @john9875621, @landv, @ssmaity57, @Jamol100, @ebrahimabdu, @blood1995, @alhamdani1, @panjibae, @dwdwow, @Julio7634, @behzad1191, @kwelton1118, @Lincoln0217, @Morty009

**Pull request merged**
